name: Test actionlint composite action

'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    name: Test actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test actionlint composite action
        uses: ./actionlint
